FileMangementMvcApp/Controllers/AuthenticationController.cs
using FileManagement.Data;
using FileManagement.Domain.Entities;
using FileMangementMvcApp.Models;
using FileMangementMvcApp.Repositories;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using BCrypt.Net;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Assignement3_Domain.Helper;

namespace FileMangementMvcApp.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IGenericRepository<User, RegisterModel> genericRepository;
        private readonly HelperMapper<User, RegisterModel, LoginModel> mapper;

        public AuthenticationController(IGenericRepository<User, RegisterModel> genericRepository,
                                        HelperMapper<User,RegisterModel ,LoginModel> mapper )
        {
            this.genericRepository = genericRepository;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            ViewBag.NotificationWrongPasswordOfUsername = TempData["NotificationWrongPasswordOfUsername"];
            ViewBag.SuccessCreatedAccountMessage = TempData["SuccessMessage"];

            return View();
        }

        public IActionResult Register()
        {
            ViewBag.NotificationAlreayExists = TempData["NotificationAlreayExists"];

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Register(RegisterModel registerModel)
        {
            // التأكد من أن اس المستخدم ليس موجود سابقا في الداتا بيز
            var existUser = await genericRepository.GetItemAsync(filter: u => u.UserName == registerModel.UserName);

            if (existUser != null)
            {
                TempData["NotificationAlreayExists"] = "This account already exists";
                return RedirectToAction("Register");
            }
            else
            {
                // توليد الملح تلقائيًا
                string salt = BCrypt.Net.BCrypt.GenerateSalt();

                // هاش كلمة المرور باستخدام BCrypt.Net والملح الذي تم توليده
                string hashedPassword = BCrypt.Net.BCrypt.HashPassword(registerModel.Password, salt);

                // لم استخدم الاوتو مابر هنا لان المابر سيكون من اجل خاصية واحدة فقط وهي خاصية اسم المستخدم
                User user = new User
                {
                    UserName = registerModel.UserName,
                    Password = hashedPassword,
                };

                // اضافة المستخدم للداتا بيز
                await genericRepository.AddAsync(user);

                TempData["SuccessMessage"] = "Your account has been successfully created. Please log in now.";

                return RedirectToAction("Index", "File");
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            // التأكد من تواجد اسم المستخدم في القاعدة
            var checkLogin = await genericRepository.GetItemAsync(filter: u => u.UserName == loginModel.UserName);

            if (checkLogin != null)
            {
                // التأكد من صحة كلمة المرور
                if (BCrypt.Net.BCrypt.Verify(loginModel.Password, checkLogin.Password))
                {
                    // Claims إذا كانت كلمة المرور صحيحة، قم بإعداد ال
                    List<Claim> claims = new List<Claim>
                    {
                       new Claim(ClaimTypes.NameIdentifier, checkLogin.Id.ToString()),
                       new Claim(ClaimTypes.Name, loginModel.UserName)
                    };

                    var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity));

                    return RedirectToAction("Index", "File");
                }
            }

            TempData["NotificationWrongPasswordOfUsername"] = "Wrong username or password";
            return RedirectToAction("Index");
        }



        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index");
        }
    }
}

FileMangementMvcApp/Controllers/FileController.cs
using Assignement3_Domain.Helper;
using AutoMapper;
using FileManagement.Data;
using FileManagement.Domain.Entities;
using FileMangementMvcApp.Models;
using FileMangementMvcApp.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.IO;
using static System.Net.WebRequestMethods;

namespace FileMangementMvcApp.Controllers
{

    [Authorize]
    public class FileController : Controller
    {
        private readonly IGenericRepository<FileUpload, FileUploadToUpdate> genericRepository;
        private readonly HelperMapper<FileUploadToAdd, FileUploadToUpdate, FileUpload> mapper;

        public FileController(IGenericRepository<FileUpload,FileUploadToUpdate> genericRepository
                              , HelperMapper<FileUploadToAdd, FileUploadToUpdate, FileUpload> mapper)
        {
            this.genericRepository = genericRepository;
            this.mapper = mapper;
        }


        // الاكشن التالية لتأخذ المستخدم لصفحة تعديل ملف 
        public async Task<IActionResult> Update(Guid id)
        {
            ViewBag.ErrorMessageInvalidExtension = TempData["ErrorMessage"];

            var file = await genericRepository.GetItemAsync(filter: f => f.Id == id);

            return View(file);
        }


        // الاكشن التالية لتأخذ المستخدم لصفحة رفع ملف 
        public IActionResult Upload()
        {
            ViewBag.MessageSelectfile = TempData["MessageSelectfile"];

            ViewBag.ErrorMessageInvalidExtension =  TempData["ErrorMessage"];

            return View();
        }

        public async Task<IActionResult> Index()
        {
            // ViewBag للحصول على الرسالة ونخزينها في TempData استخدام 
            ViewBag.ErrorMessage = TempData["ErrorMessage"];

            ViewBag.SuccessMessage = TempData["SuccessMessage"];

            
            ViewBag.Message = TempData["Message"] as string;

            // جلب كل معلومات الملفات 
            var files = await genericRepository.GetAllAsync();

            return View(files);
        }


        // ايند بوينت حذف ملف 
        [HttpPost("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                var file = await genericRepository.GetItemAsync(filter: f => f.Id == id);

                string fileNameInUploadsFolder = GetFileNameFromUploadsFolder(id, file?.Name);

                await DeleteFileWithoutReturnAnyThing(id, fileNameInUploadsFolder);

                TempData["SuccessMessage"] = "File Deleted successfully";

            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "an error occurred";
            }
            return RedirectToAction("Index");
        }



        // ايند بوينت رفع ملف 
        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file,
                                                FileUploadToAdd fileUploadToAdd)
        {
           
            if (file != null && file.Length > 0)
            {
                try
                {
                    if (!ValidExtensions(file.FileName)) // اذا كان امتداد الملف غير مسموح به 
                    {

                        return RedirectToAction("Upload");
                    }

                    // استخراج امتداد الملف 
                    string fileExtension = Path.GetExtension(file.FileName);

                    // متابعة مع التحميل والحفظ إذا كان امتداد الملف مسموح به
                    // تحديد المجلد الذي سيتم حفظ الملف المرفوع فيه 
                    string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "uploads");

                    // انشاء المجلد اذا كان غير موجود 
                    if (!Directory.Exists(uploadsFolder))
                    {
                        Directory.CreateDirectory(uploadsFolder);
                    }

                    // استخراج اسم الملف الاصلي 
                    string fileName = Path.GetFileName(file.FileName);

                    // تم توليد رقم الملف هنا لأنني سأستخدمه في وضع مسار الملف 
                    // حيث استخدمت رقم الملف وليس اسمه لكي يتخزن الملف في الهارد ويكون اسمه هو رقمه
                    // مع الامتداد الخاص به وليس الاسم الذي رُفع به لأني واجهت مشكلة عندما كان الاسم الذي رُفع به
                    var fileId = Guid.NewGuid();

                    string fileIdAsString = fileId.ToString();

                    // وضع مسار الملف 
                    string filePath = Path.Combine(uploadsFolder, fileIdAsString + fileExtension);

                    // حفظ الملف في المجلد 
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(fileStream);
                    }

                    // في الاوبجكت التالي لاداعي للاوتو مابر لأن خصائص الاوبجكت لايتم أخذها من اوبجكت اخر
                    //  عدا اخر خاصية
                    FileUpload fileUpload = new FileUpload
                    {
                        Id = fileId,
                        Path = filePath,
                        Name = fileName,
                        FileType = file.ContentType,
                        CreatedBy = User.Identity.Name,
                        Description = fileUploadToAdd.Description
                    };

                    // اضافة معلومات الملف للقاعدة 
                    await genericRepository.AddAsync(fileUpload);
                    await genericRepository.Save();

                    TempData["SuccessMessage"] = "File uploaded successfully";
                }

                catch (Exception)
                {
                    TempData["ErrorMessage"] = "an error occurred";
                }
            }
            else
            {
                TempData["MessageSelectfile"] = "Please select a file";
                return RedirectToAction("Upload");

            }

            return RedirectToAction("Index");
        }



        // ايند بوينت تعديل ملف
        [HttpPost]
        public async Task<IActionResult> Update( IFormFile file1,
                                                 FileUploadToUpdate fileUploadToUpdate)
        {
            try
            {
                var Oldfile = await genericRepository.GetItemAsync(filter: f => f.Id == fileUploadToUpdate.id);

                // هنا في حال اراد اليوزر تعديل كل الملف يعني تغيير كل الملف 
                if (file1 != null)
                {

                    if (!ValidExtensions(file1?.FileName)) // اذا كان امتداد الملف غير مسموح به 
                    {

                        return RedirectToAction("Update", new { Id = Oldfile?.Id });
                    }


                    string fileNameInUploadsFolder = GetFileNameFromUploadsFolder(Oldfile!.Id, Oldfile.Name);

                    await DeleteFileWithoutReturnAnyThing(fileUploadToUpdate.id, fileNameInUploadsFolder);

                    FileUploadToAdd fileUploadToAdd = mapper.MapperForCreate.Map<FileUploadToUpdate, FileUploadToAdd>(fileUploadToUpdate);

                    // رفع الملف الجديد 
                    await Upload(file1, fileUploadToAdd);

                    TempData["SuccessMessage"] = "File updated successfully";
                }



                // هنا في حال اراد اليوزر تعديل معلومات الملف فقط 
                else
                {
                    await genericRepository.UpdateAsync(fileUploadToUpdate.id, fileUploadToUpdate);
                    await genericRepository.Save();

                    TempData["SuccessMessage"] = "File updated successfully";
                }
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "an error occurred";
            }

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Download(Guid fileId )
        {
            var fileName = "";
            var filePath = "";

            try
            {
                var file = await genericRepository.GetItemAsync(filter: f => f.Id == fileId);

                filePath = file?.Path;
                fileName = file?.Name;

                // uploads التأكد من أن الملف موجود في المجلد 
                if (file == null || !System.IO.File.Exists(filePath))
                {
                    TempData["ErrorMessage"] = $"Error: Could not find file with name {fileName}";
                    return RedirectToAction("Index");
                }

             
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred";
                return RedirectToAction("Index");
            }

            return PhysicalFile(filePath, "application/octet-stream", fileName);
        }


        // قمت بتعريف هذه الدالة لان الكود الذي بداخلها سأحتاجه في اكثر من مكان
        // uploads حيث هي دالة تحذف معلومات الملف من القاعدة وتحذف الملف من مجلد 
        private async Task DeleteFileWithoutReturnAnyThing(Guid id, string fileNameInUploadsFolder )

        {
            // حذف معلومات الملف من القاعدة
            await genericRepository.DeleteAsync(id);

            await genericRepository.Save();

            // جلب مسار الملف من اجل حذفه من هذا المسار بعد حذفه من قاعدة البيانات
            var filePath = Path.Combine("uploads", $"{fileNameInUploadsFolder}");

            // حذف الملف إذا كان موجودا
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }
        }

        // الدالة التالية استخدمتها في اكثر من مكان والكود الذي بداخلها يتأكد بأن امتداد الملف مسموح به 
        private bool ValidExtensions(string? fileName)
        {
            // قائمة بالامتدادات المسموح بها
            List<string> allowedExtensions = new List<string> { ".jpg", ".jpeg", ".png", ".gif", ".pdf" };

            // جلب امتداد الملف
            string fileExtension = Path.GetExtension(fileName);

FileMangementMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FileMangementMvcApp.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300&display=swap" rel="stylesheet">
    <title>@ViewData["Title"]</title>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand mb-2" asp-area="" asp-controller="Home" asp-action="Index">FileMangementMvcApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">








                        @if (User.Identity.IsAuthenticated)
                        {
                             <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="File" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item ml-auto">
                        <a class="btn my-2 my-sm-0 btn-md LogoutBtn" href="/Authentication/Logout" type="submit">
                        Logout
                        <i class="fa-solid fa-arrow-left fa-rotate-180 pb-1 " style="color: black;"></i>
                        <span class="sr-only">(current)</span>
                        </a>
                        </li>
                            
                        }
                        else
                        {
                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item ml-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="index">Sign in </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Register">Sign up</a>
                            </li>
                        }








                        @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="btn my-2 my-sm-0 btn-md LogoutBtn" href="/Authentication/Logout" type="submit">
                                Logout
                                <i class="fa-solid fa-arrow-left fa-rotate-180 pb-1 " style="color: black;"></i>
                                <span class="sr-only">(current)</span>
                            </a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1445 - FileMangementMvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <partial name = "_ValidationScriptsPartial" />


</body>
</html>

FileMangementMvcApp/Views/Shared/_LayoutAuth.cshtml
 @* الملف التالي اصبح غير مستخدم  *@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FileMangementMvcApp.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300&display=swap" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">File Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="index">Sign in </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Register">Sign up</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1445 - FileMangementMvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <partial name = "_ValidationScriptsPartial" />
</body>
</html>