FileMangementMvcApp/Controllers/FileController.cs
using Assignement3_Domain.Helper;
using AutoMapper;
using FileManagement.Data;
using FileManagement.Domain.Entities;
using FileMangementMvcApp.Models;
using FileMangementMvcApp.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.IO;
using static System.Net.WebRequestMethods;

namespace FileMangementMvcApp.Controllers
{

    [Authorize]
    public class FileController : Controller
    {
        private readonly IGenericRepository<FileUpload, FileUploadToUpdate> genericRepository;
        private readonly HelperMapper<FileUploadToAdd, FileUploadToUpdate, FileUpload> mapper;

        public FileController(IGenericRepository<FileUpload,FileUploadToUpdate> genericRepository
                              , HelperMapper<FileUploadToAdd, FileUploadToUpdate, FileUpload> mapper)
        {
            this.genericRepository = genericRepository;
            this.mapper = mapper;
        }


        // الاكشن التالية لتأخذ المستخدم لصفحة تعديل ملف 
        public async Task<IActionResult> Update(Guid id)
        {
            ViewBag.ErrorMessageInvalidExtension = TempData["ErrorMessage"];

            var file = await genericRepository.GetItemAsync(filter: f => f.Id == id);

            return View(file);
        }


        // الاكشن التالية لتأخذ المستخدم لصفحة رفع ملف 
        public IActionResult Upload()
        {
            ViewBag.MessageSelectfile = TempData["MessageSelectfile"];

            ViewBag.ErrorMessageInvalidExtension =  TempData["ErrorMessage"];

            return View();
        }

        public async Task<IActionResult> Index()
        {
            // ViewBag للحصول على الرسالة ونخزينها في TempData استخدام 
            ViewBag.ErrorMessage = TempData["ErrorMessage"];

            ViewBag.SuccessMessage = TempData["SuccessMessage"];

            
            ViewBag.Message = TempData["Message"] as string;

            // جلب كل معلومات الملفات 
            var files = await genericRepository.GetAllAsync();

            return View(files);
        }


        // ايند بوينت حذف ملف 
        [HttpPost("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                var file = await genericRepository.GetItemAsync(filter: f => f.Id == id);

                string fileNameInUploadsFolder = GetFileNameFromUploadsFolder(id, file?.Name);

                await DeleteFileWithoutReturnAnyThing(id, fileNameInUploadsFolder);

                TempData["SuccessMessage"] = "File Deleted successfully";

            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "an error occurred";
            }
            return RedirectToAction("Index");
        }



        // ايند بوينت رفع ملف 
        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file,
                                                FileUploadToAdd fileUploadToAdd)
        {
           
            if (file != null && file.Length > 0)
            {
                try
                {
                    if (!ValidExtensions(file.FileName)) // اذا كان امتداد الملف غير مسموح به 
                    {

                        return RedirectToAction("Upload");
                    }

                    // استخراج امتداد الملف 
                    string fileExtension = Path.GetExtension(file.FileName);

                    // متابعة مع التحميل والحفظ إذا كان امتداد الملف مسموح به
                    // تحديد المجلد الذي سيتم حفظ الملف المرفوع فيه 
                    string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "uploads");

                    // انشاء المجلد اذا كان غير موجود 
                    if (!Directory.Exists(uploadsFolder))
                    {
                        Directory.CreateDirectory(uploadsFolder);
                    }

                    // استخراج اسم الملف الاصلي 
                    string fileName = Path.GetFileName(file.FileName);

                    // تم توليد رقم الملف هنا لأنني سأستخدمه في وضع مسار الملف 
                    // حيث استخدمت رقم الملف وليس اسمه لكي يتخزن الملف في الهارد ويكون اسمه هو رقمه
                    // مع الامتداد الخاص به وليس الاسم الذي رُفع به لأني واجهت مشكلة عندما كان الاسم الذي رُفع به
                    var fileId = Guid.NewGuid();

                    string fileIdAsString = fileId.ToString();

                    // وضع مسار الملف 
                    string filePath = Path.Combine(uploadsFolder, fileIdAsString + fileExtension);

                    // حفظ الملف في المجلد 
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(fileStream);
                    }

                    // في الاوبجكت التالي لاداعي للاوتو مابر لأن خصائص الاوبجكت لايتم أخذها من اوبجكت اخر
                    //  عدا اخر خاصية
                    FileUpload fileUpload = new FileUpload
                    {
                        Id = fileId,
                        Path = filePath,
                        Name = fileName,
                        FileType = file.ContentType,
                        CreatedBy = User.Identity.Name,
                        Description = fileUploadToAdd.Description
                    };

                    // اضافة معلومات الملف للقاعدة 
                    await genericRepository.AddAsync(fileUpload);
                    await genericRepository.Save();

                    TempData["SuccessMessage"] = "File uploaded successfully";
                }

                catch (Exception)
                {
                    TempData["ErrorMessage"] = "an error occurred";
                }
            }
            else
            {
                TempData["MessageSelectfile"] = "Please select a file";
                return RedirectToAction("Upload");

            }

            return RedirectToAction("Index");
        }



        // ايند بوينت تعديل ملف
        [HttpPost]
        public async Task<IActionResult> Update( IFormFile file1,
                                                 FileUploadToUpdate fileUploadToUpdate)
        {
            try
            {
                var Oldfile = await genericRepository.GetItemAsync(filter: f => f.Id == fileUploadToUpdate.id);

                // هنا في حال اراد اليوزر تعديل كل الملف يعني تغيير كل الملف 
                if (file1 != null)
                {

                    if (!ValidExtensions(file1?.FileName)) // اذا كان امتداد الملف غير مسموح به 
                    {

                        return RedirectToAction("Update", new { Id = Oldfile?.Id });
                    }


                    string fileNameInUploadsFolder = GetFileNameFromUploadsFolder(Oldfile!.Id, Oldfile.Name);

                    await DeleteFileWithoutReturnAnyThing(fileUploadToUpdate.id, fileNameInUploadsFolder);

                    FileUploadToAdd fileUploadToAdd = mapper.MapperForCreate.Map<FileUploadToUpdate, FileUploadToAdd>(fileUploadToUpdate);

                    // رفع الملف الجديد 
                    await Upload(file1, fileUploadToAdd);

                    TempData["SuccessMessage"] = "File updated successfully";
                }



                // هنا في حال اراد اليوزر تعديل معلومات الملف فقط 
                else
                {
                    await genericRepository.UpdateAsync(fileUploadToUpdate.id, fileUploadToUpdate);
                    await genericRepository.Save();

                    TempData["SuccessMessage"] = "File updated successfully";
                }
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "an error occurred";
            }

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Download(Guid fileId )
        {
            var fileName = "";
            var filePath = "";

            try
            {
                var file = await genericRepository.GetItemAsync(filter: f => f.Id == fileId);

                filePath = file?.Path;
                fileName = file?.Name;

                // uploads التأكد من أن الملف موجود في المجلد 
                if (file == null || !System.IO.File.Exists(filePath))
                {
                    TempData["ErrorMessage"] = $"Error: Could not find file with name {fileName}";
                    return RedirectToAction("Index");
                }

             
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred";
                return RedirectToAction("Index");
            }

            return PhysicalFile(filePath, "application/octet-stream", fileName);
        }


        // قمت بتعريف هذه الدالة لان الكود الذي بداخلها سأحتاجه في اكثر من مكان
        // uploads حيث هي دالة تحذف معلومات الملف من القاعدة وتحذف الملف من مجلد 
        private async Task DeleteFileWithoutReturnAnyThing(Guid id, string fileNameInUploadsFolder )

        {
            // حذف معلومات الملف من القاعدة
            await genericRepository.DeleteAsync(id);

            await genericRepository.Save();

            // جلب مسار الملف من اجل حذفه من هذا المسار بعد حذفه من قاعدة البيانات
            var filePath = Path.Combine("uploads", $"{fileNameInUploadsFolder}");

            // حذف الملف إذا كان موجودا
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }
        }

        // الدالة التالية استخدمتها في اكثر من مكان والكود الذي بداخلها يتأكد بأن امتداد الملف مسموح به 
        private bool ValidExtensions(string? fileName)
        {
            // قائمة بالامتدادات المسموح بها
            List<string> allowedExtensions = new List<string> { ".jpg", ".jpeg", ".png", ".gif", ".pdf" };

            // جلب امتداد الملف
            string fileExtension = Path.GetExtension(fileName);

FileMangementMvcApp/Views/File/Index.cshtml
@* هذه الفيو ستحوي على جدول يتم عرض جميع الملفات المخزنة 
في قاعدة البيانات وكل سطر فيه زر حذف وزر تعديل وزر تنزيل الملف ويحوي هذا الملف في  مكان ما
زر لرفع الملف وعند الضغط عليه يتم اخذ اليوزر على صفحة  
الرفع اللي بيختار منها  الزبون الملف اللي بدو يرفعو وبأدخل معلومات بالحقول المطلوبة *@
@using FileManagement.Domain.Entities
@model List<FileUpload> 


@{
    ViewData["Title"] = "All files";
}



<link href="~/css/FileIndexStyle.css" rel="stylesheet" />

<div class="form-group text-center">
    <label class="text-center text-dark fs-5"> @ViewBag.Message</label>
</div>

<div class="form-group text-center">
    <label class="text-center text-danger fs-5"> @ViewBag.ErrorMessage</label>
</div>
 

<div class="form-group text-center">
    <label class="text-center text-success fs-5"> @ViewBag.SuccessMessage</label>
</div>

@* في حال كان المودال فارغ لن يتم اظهار الجدول *@
         @if (Model.Any())
        {
            <div class="row">
                <div class="col-12 d-flex justify-content-center">
            <h2 class="text-center text-info mb-5" style="  font-weight: 80;">All Files</h2>
                </div>
            </div>

            <div class="row">
                <div class="col-12 d-flex justify-content-center">
                     <table class="table table-striped ">
                          <thead class="thead-dark">
                             <tr>
                                   <th scope="col" class='text-center'>File name</th>
                                   <th scope="col" class='text-center'>CreatedBy </th>
                                   <th scope="col" class='text-center'>CreateAt</th>
                                   <th scope="col" class='text-center'> Description</th>
                                   <th scope="col" class='text-center'>  </th>
                                   <th scope="col" class='text-center'>  </th>
                                   <th scope="col" class='text-center'>  </th>
                             </tr>
                          </thead>

                         <tbody>
               
                            @foreach (var file in Model)
                            {
                                <tr>
                                    <td>@file.Name</td>
                                    <td>@file.CreatedBy</td>
                                    <td>@file.CreatedAt</td>
                                    <td>@file.Description</td>
                                    <td>
                                        <form asp-action="Delete" asp-controller="File" asp-route-id="@file.Id" method="post">
                                            <button type="submit" value="Delete" class="btn btn-danger" />
                                            Delete
                                            <button />
                                        </form>
                                    </td>

                                    <td>
                                        <a asp-action="Download" asp-controller="File" asp-route-fileId="@file.Id"
                                           class="btn btn-primary">
                                            Download
                                        </a>
                                    </td>

                                    <td>
                                        <a class="btn btn-primary" asp-action="Update" , asp-controller="File" asp-route-id="@file.Id">
                                            Update
                                        </a>
                                    </td>
                                </tr>
                            }
                

                        </tbody>
                  </table>
                </div>
            </div>
        }

        else
        {
              <div class="row">
                  <div class="col-12 d-flex justify-content-center mb-5">
                      <h2>No files available.</h2>
                  </div>
              </div>

        }
  
        @* انشاء سطر لزر الرفع *@
<div class="row">
    <div class="col-12 d-flex justify-content-center mt-4">
        <a class="btn btn-primary " asp-action="Upload" asp-controller="File">
            Upload file
        </a>
    </div>
</div>




























 

FileMangementMvcApp/Views/File/Update.cshtml
@using FileManagement.Domain.Entities
@model FileUpload

@{
    ViewData["Title"] = "Update File";
}
<style>
.validation-summary-errors ul li {
    display: none;
}
</style>

<div class="text-center">
    <label class=" text-danger  fs-5" m-auto> @ViewBag.ErrorMessageInvalidExtension</label>
</div>

@if (Model != null)
{
    <div class="card m-auto" style="width: 40rem;" >
        <div class="card-body">
            <h5 class="card-title text-center">Update File</h5>
            <form asp-action="Update" asp-controller="File"
            enctype="multipart/form-data" method="post"
            style="margin: 0; display: flex; justify-content: center; align-items: center;">
                <div asp-validation-summary="All" class="text-danger">
                </div>
                <div class="container-fluid">
                    <input type="hidden" name="id" asp-for="@Model.Id" value="@Model?.Id" />

                    <div class="form-group">
                        <label for="file">Select file to update</label>
                        <div class="input-group">
                            <input id="file" name="file1" type="file" class="form-control" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label asp-for="@Model.Description">Description</label>
                        <div class="input-group">
                            <input type="text" class="form-control" asp-for="@Model.Description"
                            aria-label="Text input with checkbox" name="Description" />
                        </div>
                    </div>


                    <div class="row" >
                        <div class="col-12">
                            <span asp-validation-for="@Model.Description" class="text-danger"></span>
                        </div>
                    </div>




                    <div class="form-group d-inline" >
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>

                    <div class="form-group d-inline text-white">
                        <a type="submit" class="btn btn-secondary" asp-action="Index" asp-controller="File">Cancel</a>
                    </div>
                </div>

            </form>
        </div>
    </div>
}

FileMangementMvcApp/Views/File/Upload.cshtml
@using FileManagement.Domain.Entities
@model FileUploadToAdd

@{
    ViewData["Title"] = "Upload file";
}
<style>
    .validation-summary-errors ul li {
        display: none;
    }
</style>
<div class="text-center">
    <label class=" text-primary  fs-5" m-auto> @ViewBag.MessageSelectfile</label>
</div>
<div class="text-center">
    <label class=" text-danger  fs-5" m-auto> @ViewBag.ErrorMessageInvalidExtension</label>
</div>

<div class="card m-auto" style="width: 40rem;">
    <div class="card-body">
        <h5 class="card-title text-center">Upload File</h5>
        <form asp-action="Upload" asp-controller="File"
              enctype="multipart/form-data" method="post"
              style="margin: 0; display: flex; justify-content: center; align-items: center;">
            <div asp-validation-summary="All" class="text-danger">
            </div>
            <div class="container-fluid">

                <div class="form-group">
                    <label for="file" >Select file for upload</label>
                    <div class="input-group">
                        <input id="file" name="file" type="file" class="form-control" />
                    </div>
                </div>

                <div class="form-group">
                    <label for="@Model?.Description">Description</label>
                    <div class="input-group">
                        <input type="text" class="form-control" asp-for="@Model.Description"
                               aria-label="Text input with checkbox" name="Description" />
                    </div>
                </div>


                <div class="row">
                    <div class="col-12">
                        <span asp-validation-for="@Model.Description" class="text-danger"></span>
                    </div>
                </div>




                <div class="form-group d-inline" >
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>

                <div class="form-group d-inline text-white" style=" color :white;">
                    <a type="submit" class="btn btn-secondary" asp-action="Index" asp-controller="File">Cancel</a>
                </div>
            </div>

        </form>
    </div>
</div>